import { Header } from '@/components/ui/header/header';
import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={'overflow-x-hidden p-medium bg-primary1'}>
        <Header size="large" textColor="primary"></Header>
        {children}
      </body>
    </html>
  );
}
